CREATE TABLE SFTP_METADATA_STORE (
METADATA_KEY VARCHAR(255) NOT NULL,
METADATA_VALUE VARCHAR(4000),
REGION VARCHAR(100) NOT NULL,
constraint SFTP_METADATA_STORE_PK primary key (METADATA_KEY, REGION)
);